### ISSUE TITLE
[Bug 0.6.3]: Expression does not evaluate to an iteratable 

### ISSUE THREAD

**Issue by Shtoyan** [EliotVU/UnrealScript-Language-Service#164]
### Describe the bug

I saw this error accidentally, don't know how to reliably reproduce it. Fixes when you add curly brackets.

- [example 1](https://github.com/InsultingPros/KillingFloor/blob/main/Engine/Classes/GameReplicationInfo.uc#L138-L139)
- [example 2](https://github.com/InsultingPros/KillingFloor/blob/main/Engine/Classes/PhysicsVolume.uc#L186-L187)

### Screenshots

![image](https://user-images.githubusercontent.com/22412356/218184816-d7c8f492-a1d7-4a0f-bf55-61960dc42472.png)

**Comment by EliotVU** [comment]
Yeah, basically the parser picks this expression up as a binary expression.

UnrealScript has this odd feature where you can define a new binary operator with an [a-z] identifier, like for instance the Dot operator.

So, the parser sees this as follows:
> forEachStatement > ExpressionStatement > BinaryExpression (left: DynamicActors(), operator: AddPRI, right: (PRI) as a ParenthesizedExpression)

**Comment by EliotVU** [comment]
A proper fix would be to delay the parsing of function blocks entirely until all related documents have been indexed. Once indexed, all the functions can be re-parsed with the knowledge of indexed binary operators, so that a non-binary identifier cannot be mistaken for one. (this is how the actual compiler works).
