### ISSUE TITLE
[0.4.4] Arrays

### ISSUE THREAD

**Issue by Xymanek** [EliotVU/UnrealScript-Language-Service#32]
Generic arguments are not recognized but non-generic (eg. `Remove`) are fine
![image](https://user-images.githubusercontent.com/2865341/71415331-c495f080-2663-11ea-83c5-1555df58fc30.png)
![image](https://user-images.githubusercontent.com/2865341/71415375-03c44180-2664-11ea-8cca-3162eb5ea258.png)

There is also a `RandomizeOrder` function which isn't recognized. I suspect that it's a Firaxis addition since I can find uses only inside `XComGame`
![image](https://user-images.githubusercontent.com/2865341/71415443-6ddce680-2664-11ea-8ff9-75fb830c61e8.png)

**Comment by midnight-dev** [comment]
Assuming `FindDLCDelegates` is a global array, `Remove` is a method, not an argument. It _looks_ like lexer is having trouble with the delegate, however, it may have glitched out on `Find` and `AddItem` instead. The IntelliSense shows `AddItem` with nothing passed into it. This could just be poorly generated documentation. "Unexpected argument" is a little ambiguous, but it can certainly mean it didn't expect an argument in the first place, even though adding and finding methods clearly need some input. Either way, you're right that this is malfunctioning. Fingers crossed it's not generic objects it's having trouble with, because those things are tricky enough as is.

What happens if you pass in a different variable there instead of `InDelegate`? 

If you right-click > go to definition on the `Remove` and `AddItem` methods, is there any significant difference to them (for instance, missing / broken doc blocks or a missing `@param` remark in said doc block)?

**Comment by Xymanek** [comment]
The issue happens for all array contents types
![image](https://user-images.githubusercontent.com/2865341/71422902-1d7a7e80-268e-11ea-949f-09da36c6277a.png)

Also for local arrays:
![image](https://user-images.githubusercontent.com/2865341/71422935-5a467580-268e-11ea-9151-cf3c17f51b6a.png)
![image](https://user-images.githubusercontent.com/2865341/71422944-629eb080-268e-11ea-9465-df18f795c6d8.png)

The `Find` method is also broken:
![image](https://user-images.githubusercontent.com/2865341/71422997-d17c0980-268e-11ea-93d0-faaa12dd68be.png)

> If you right-click > go to definition on the `Remove` and `AddItem` methods

Nothing happens (for all of them):
![image](https://user-images.githubusercontent.com/2865341/71422954-75b18080-268e-11ea-872d-f841cfd568c9.png)
